### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by rlambertsen** [vue-comps/vue-zoombox#1]
Is there a way to make the thumbnails responsive like the zoombox image is?

**Comment by paulpflug** [comment]
what do you mean precisely? you can make the thumbnail smaller with for example css, like any image..

**Comment by rlambertsen** [comment]
The thumbnail image has inline css, am I able to change that in my .vue file?

**Comment by paulpflug** [comment]
ah I see the problem.
`:style` should overwrite it, but I'm working on an even nicer solution.

**Comment by paulpflug** [comment]
could you elaborate how you make your images smaller on smaller screens, what would be the best way?

**Comment by rlambertsen** [comment]
I would do what [Bootstrap](http://www.w3schools.com/bootstrap/bootstrap_ref_css_images.asp) does:

> The .img-responsive class applies max-width: 100%, height: auto, and display:block to the image

That makes the image fluid and stay inside the images parent element. Try that

**Comment by paulpflug** [comment]
please report back if you encounter any problems
