### ISSUE TITLE
Animation not working

### ISSUE THREAD

**Issue by jankincl** [vue-comps/vue-zoombox#2]
Thanks for creating this component. I like a lot the fade animation which is in the demo, but I am unable to get it to work in my project. Can you show exactly what code you use to define the animation and where to place it? Isn't there a default animation in place somehow?

**Comment by paulpflug** [comment]
hey,
If you want a default animation you can use [material-box](https://github.com/paulpflug/vue-materialize#material-box-top). That is basically `vue-zoombox` plus animations. The `material-box` doesn't need any styles, so you can simply run `npm install vue-materialize` and then `require("vue-materialize/material-box")`

If you want to use your own animations, see [basic.vue](https://github.com/vue-comps/vue-zoombox/blob/master/dev/basic.vue) for an example.

There are 3 different animations, one for the [overlay](https://github.com/vue-comps/vue-zoombox/blob/master/dev/basic.vue#L25-L31), one for the [caption](https://github.com/vue-comps/vue-zoombox/blob/master/dev/basic.vue#L64-L81), and one for the [box](https://github.com/vue-comps/vue-zoombox/blob/master/dev/basic.vue#L43-L63)

**Comment by jankincl** [comment]
Thanks. I used now the material-box instead and it works out of the box with the animation, so it's perfect. Thanks!
